name: 'Student'
version: '1.0.0'
config-version: 2
profile: 'default'

models:
  Student: 
    staging:
      materialized: 'view'
    intermediate:
      materialized: 'view'
    marts:
      materialized: 'table'
      finance:
        schema: finance



