version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: raw_product
        identifier: raw_gz_product
      - name: raw_sales
        identifier: raw_gz_sales
      - name: raw_ship
        identifier: raw_gz_ship

